# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/nativescript-demo
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install npm modules
          command: |
            npm i --no-progress --ignore-scripts;
            ./node_modules/.bin/tns usage-reporting disable && ./node_modules/.bin/tns error-reporting disable;

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Build setup
          command: |
            echo $ANDROID_KEY_BASE64 | base64 -d > ./key.jks;
            echo $PLAY_STORE_JWT > ./jwt.json;
            rm -rf platforms;
            ./node_modules/.bin/tns platform add android;
            cp ./app/App_Resources/Android/gradle.properties ./platforms/android/gradle.properties;

      - run:
          name: Build signed app
          environment:
            ANDROID_KEY_BASE64: ""
            PLAY_STORE_JWT: ""
          command: |
            ./node_modules/.bin/tns build android --release --clean --key-store-path ./key.jks --key-store-password "${KEY_STORE_PASSWORD}" --key-store-alias "${KEY_STORE_ALIAS}" --key-store-alias-password "${KEY_STORE_ALIAS_PASSWORD}" --copy-to ./dist/soon-app-demo.apk;

      - run:
          name: Publish app
          command: |
            node ./scripts/upload-package.js

      - store_artifacts:
          path: ./dist

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
